### ISSUE TITLE
想问一下为什么有的连线是虚线，有的是实线？什么情况下是虚线呢？

### ISSUE THREAD

**Issue by weiweibupt** [caoyu48/vue-g6-editor#8]
想问一下为什么有的连线是虚线，有的是实线？什么情况下是虚线呢？

**Comment by weiweibupt** [comment]
@caoyu48 如果方便的话希望您帮我解答一下，非常感谢~

**Comment by caoyu48** [comment]
虚线是动画

**Comment by weiweibupt** [comment]
> 虚线是动画

感谢您的回答~为什么我一开始拖拽连线的时候出现了虚线，现在新画图又没有了呢，这个控制写在哪个文件，

> 虚线是动画

非常感谢您的回答~我明白la~

**Comment by caoyu48** [comment]
你说的那个虚线啊。。。   behavior/add-edge.js
